name: Deploy Yew App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: stable

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk wasm-bindgen-cli

      - name: Build with Trunk
        run: trunk build --release

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
